export default [
    {
        pagePath:"/pages/home/index",
        text:"攻略",
        iconPath:"/assets/icons/sword.png",
        selectedIconPath:"/assets/icons/sword-selected.png"
    },
    {
        pagePath:"/pages/hero/index",
        text:"英雄",
        iconPath:"/assets/icons/hero.png",
        selectedIconPath:"/assets/icons/hero-selected.png"
    },
    {
        pagePath:"/pages/equipment/index",
        text:"装备",
        iconPath:"/assets/icons/equipment.png",
        selectedIconPath:"/assets/icons/equipment-selected.png"
    },
    {
        pagePath:"/pages/hex/index",
        text:"强化",
        iconPath:"/assets/icons/tft.png",
        selectedIconPath:"/assets/icons/tft-selected.png"
    },
    {
        pagePath:"/pages/mine/index",
        text:"设置",
        iconPath:"/assets/icons/option.png",
        selectedIconPath:"/assets/icons/option-selected.png"
    }
]
