const SESSION = "__SESSION__"
const SESSION_LIST = "__SESSION_LIST__"
const FEEDBACK_APPID = "wx8abaf00ee8c3202e"
const OBJECT = 474934
module.exports = {SESSION, FEEDBACK_APPID, OBJECT, SESSION_LIST}
