const SESSION = "__SESSION__"
const SESSION_SHOW_NICKNAME = '__SESSION_SHOW_NICKNAME__'
const SESSION_LIST = "__SESSION_LIST__"
const FEEDBACK_APPID = "wx8abaf00ee8c3202e"
const OBJECT = 474934
const DEFAULT_SESSION = "s9"
const API_DOMAIN = "https://tft.qizue.com"
module.exports = {SESSION, FEEDBACK_APPID, OBJECT, SESSION_LIST, API_DOMAIN, SESSION_SHOW_NICKNAME, DEFAULT_SESSION}
