const SESSION = "__SESSION__"
const SESSION_SHOW_NICKNAME = '__SESSION_SHOW_NICKNAME__'
const SESSION_FOLDING_MID_PROPHASE = '__SESSION_FOLDING_MID_PROPHASE__'
const SESSION_SHOW_ORIGIN_SKIN = '__SESSION_SHOW_ORIGIN_SKIN__'
const SESSION_LIST = "__SESSION_LIST__"
const SESSION_SET = "__SESSION_SET__"
const FEEDBACK_APPID = "wx8abaf00ee8c3202e"
const OBJECT = 474934
const DEFAULT_SESSION = "s9.5"
const DEFAULT_SESSION_NAME = "志逐天际"
const API_DOMAIN = "https://tft.qizue.com"
module.exports = {SESSION, FEEDBACK_APPID, OBJECT, SESSION_LIST, API_DOMAIN,
    SESSION_SHOW_NICKNAME, DEFAULT_SESSION, SESSION_SET,
    DEFAULT_SESSION_NAME, SESSION_FOLDING_MID_PROPHASE, SESSION_SHOW_ORIGIN_SKIN}
